[[Cares]]
arch = "aarch64"
git-tree-sha1 = "bcb22995665f728bed1c3e6d8c1824aa3fc03f6c"
os = "macos"

    [[Cares.download]]
    sha256 = "dfe2e857c15acc8f68ed62298b2534c27e987589c309efbcd278e8f07040d904"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.aarch64-apple-darwin.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "71bb55c534a7ee97b0da7db1c4b9dfb3f6f5cb7d"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "6ae095fb673405360cd0904bd959d4a2efdf48a57e57ffa3e553fad6c9eaff81"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.aarch64-linux-gnu.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "e1757c4bed6070d6b9ba02308ef0ac22ac522b98"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "3619ef94bd7cf4568e759d242ee906b01a35c487eb29a1b0f30e793b91d82826"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.aarch64-linux-musl.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "258e0600a149d02f4fe70ae5bf57f79e304908ae"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "4e93a094fe2874854b38015d9c30fa7ce870a9d62cfd440a9793f4bad6742682"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.armv6l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a695ffb0b094189c1a5c72b1b393f03b13c00365"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "c8498499e2a45e5b56d73264307c9ef3e1e7ae5ba51e22627be668635f4c0f28"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.armv6l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "660814b3f5a483795d1e7d08041e28f0714754f8"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "57b3007974b3cbc39c3078b368dc2bf047af63b3e98c7038bd9544d004bd2f47"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.armv7l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "292883b0b6834f344a1e99927c717d60dd831b6d"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "a5f6f276e5a871eb4c9882510cf35061fb73a3808f74f17abb0a0fa1fc08c7fe"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.armv7l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "3332e5ce2233579b088a93261a1f947a568313f3"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "3d3def45cd6200e94ac387461dbb2b413babba8e748685f2059d546916ec1f17"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.i686-linux-gnu.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "feeebc8ddf90449229d96258ee380e74ff86dcb4"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "515e939ac193c766c34377d7ecdbfd3d88c74dd1dcb60b33cea55932a906ffd5"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.i686-linux-musl.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "e7938378d28ee0e716f69c66454fe40fff401dc7"
os = "windows"

    [[Cares.download]]
    sha256 = "6d982ea33316720c81fd760960b877fc1b872abfd8d4b59af95c3932ea42c28a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.i686-w64-mingw32.tar.gz"
[[Cares]]
arch = "powerpc64le"
git-tree-sha1 = "ac3897956101ae340416075f3d0802d2dc562712"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "31cc73196e459c53f83b548878dc69c6c3458aa0b3b760b57948f67b80f99332"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.powerpc64le-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "855fda607978897e7179f891f120f46689916304"
os = "macos"

    [[Cares.download]]
    sha256 = "4ef66f75c0dac7826c1b96661ffb7e88240e391378b6c3f55764b70857ee57fc"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.x86_64-apple-darwin.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "b8994f0e5aff0fc3dc101e957210f1e27af029e0"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "a937f91e836a69efe22928a2143e8b30004cd9e800889ff5f80b220a6c4517c9"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.x86_64-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "ee66ffad6fda922c03cb78d6c65f02ecb6609db5"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "125867ebce0179d80648327f3cf67d5eddb21fa381cdcfeb0b0a27962fa5b37a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.x86_64-linux-musl.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "c3c383399946f23059f5b19d9faa42517eb4a861"
os = "freebsd"

    [[Cares.download]]
    sha256 = "01472e9732a7f4ed920ef233c460a4de1bfb66efc70527aad21082e184f13521"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.x86_64-unknown-freebsd.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "63bb71380e2d17ed9555fec398637952023d7758"
os = "windows"

    [[Cares.download]]
    sha256 = "40cf8374df5ea2f4176e1a9cd0cb9232c09fdbf199bb1f62823fde1416c1d431"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.23.0+0/Cares.v1.23.0.x86_64-w64-mingw32.tar.gz"
