[[Cares]]
arch = "aarch64"
git-tree-sha1 = "544ecac8ec3217d503e33547679cfb283807cb72"
os = "macos"

    [[Cares.download]]
    sha256 = "742f550f736d215393ad6e39a6019709bb0116fd695c82723a8684eec9bceff4"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.aarch64-apple-darwin.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "c864be0d2d5c5ec2f609cce0a880aab3458862dc"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "67fdc378e90ed9bf5be2bfeac826c0b596963026e75cda4b39b712e077eeba92"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.aarch64-linux-gnu.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "c93547cc872d8055091e141b2eb2d111fe74865b"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "5a6a37c389982e3f8449164a566f5aa6f3a41c11ab6f0008c88dcb05d99457a0"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.aarch64-linux-musl.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aae657a637f6f99c2b21c486e1d3190a322d726f"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "6f5149b12c3d6471674cf9853dc6ff3cedf75a65ab7d762a24e8e73d31a5c34d"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.armv6l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ee4575389b7277cb893ff4dbe79cb950cb489b14"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "bfb96c96e2e44b070338cebc35256bc9f37aab2110577d4a757760b4f2ac718a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.armv6l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2543eea4a81eac259fc5e56dd7f121c8dd867c2"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "27c91818b7b18c546089afe0e021c69135fe523bd935ce694e23459c5c0640e0"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.armv7l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b68a83b8c1f9ee4a3b1ad80c14cab854ac7279d1"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "db2e3e0f01f6b82eebeb472134a5e108a30d2dd772abc1c4662709f5b1320d52"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.armv7l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "2802c91edbfc18594b47ec42df746a2a195e09f2"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "d09a271ac444ba9e5a7ebaf030ab5975e73f93f3a1403c3f597868d634d6d56a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.i686-linux-gnu.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "f769d161247e60a9e324437e59ace4428ff499c1"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "528266ffadac2e566344cd349fce05b5f5ff386794d2b4d7c10577904516d17d"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.i686-linux-musl.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "ccb3f26f31a12f82d97d04b87d172508cef00230"
os = "windows"

    [[Cares.download]]
    sha256 = "e788388c122232f29fdd237956c8bd46ae78ead72468752fdf342ca5f706184e"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.i686-w64-mingw32.tar.gz"
[[Cares]]
arch = "powerpc64le"
git-tree-sha1 = "511fd96549184a7f42b9003dbeb6334c5800ea5c"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "4698abf4fa1f424fc023b3647d860825b5666793177e33ebed68c5f317053c6e"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.powerpc64le-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "e9c31d95a9fe19883744f6b7dc0414437aa6077a"
os = "macos"

    [[Cares.download]]
    sha256 = "549a7a401993618a18866a09a8fe32c5d0995f7a82acd990cc192387e03b8ce3"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.x86_64-apple-darwin.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "d9161b25d394c13419003d4467a06f97d76ae126"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "3288c8719674db2e9d177884f5c31c1c486c034999c175f72149846900d57639"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.x86_64-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "c8d9556480ed2c48f9fd669c8b598be7b8b7bf9b"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "ce79f6bc22e5b4fe170b415115e3bc31c2fa593107bff462547dc24b9a33ac7d"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.x86_64-linux-musl.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "76a77bf8df179537b0878586e84143fd54cf2b71"
os = "freebsd"

    [[Cares.download]]
    sha256 = "4d39410e43b0e51fe9fd3308bba3c7ba49b32ad31b5fad351ed8b44caacb9a1c"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.x86_64-unknown-freebsd.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "228ef90844fbc4b937ee663811607814c48da90c"
os = "windows"

    [[Cares.download]]
    sha256 = "2662aa16ad42b965d531b190aea0babb6dbfff82a5f3fa9120f86e58eb104b8d"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.2+0/Cares.v1.32.2.x86_64-w64-mingw32.tar.gz"
