[[Cares]]
arch = "aarch64"
git-tree-sha1 = "9c8c85a1dcf57a66a4d8484804dfbbd38b38e183"
os = "macos"

    [[Cares.download]]
    sha256 = "95b2ea6ab0f373e02ed38f00d5861cc454a7e07386266cc81260d133ab61ec0a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.aarch64-apple-darwin.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "61ff92b2b088037b27528d1788f50d438a8ac54a"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "8e09f69473f5fe6d32d70ae5e8f49ffab733fdd743a582029ad0b392cec4763a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.aarch64-linux-gnu.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "e5b2cfeb078b5f123d93ef86868af8d5cb810ce5"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "6aa1c1c6413c7299748df903d046caf1142ba52eed40901597e0b83336439ea5"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.aarch64-linux-musl.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5bed7dd80dbce52acd6a581bcc6e9cf5c47c54f9"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "706521f511aabc4e0b93ad5dce51ae3d8fc1d5ef86681f40ef87b5c876f3dd29"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.armv6l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0a462b3b875a1a997f7f085fd9a3c5311fba9312"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "cf30298f66f97be29ac206d85fed385c72e6c4521f700a9dbdcd4fe07aa56311"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.armv6l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4e76c798eb816e8fa5fb6937837e6db45da652aa"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "f80b43c79bb914a5f2947434df6f7fbd760fe750fed5eb2bdd73121dcc2360d6"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.armv7l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2692bcbf53579eb55cd53423f81c7e16dad3be3d"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "050841ac81254731738f686a0b8a617e1f62fa480fd618d831aa806e90e8c76d"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.armv7l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "f9259d1d7fe3f965e5e8615231310f65ab583aa8"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "d26011fa15203ed7e4f67e3430ef6f28177ecc3359a73aef2d54c99b7a7bfb3f"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.i686-linux-gnu.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "8f60307ae3a1f41586122dc1d542fb9807a04850"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "af24230f3ca492bdb9a393cfb851f52bad19e1b7caa578258c600177bd41d98f"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.i686-linux-musl.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "2690109aaa012b6a292b904d14828e5daffcd423"
os = "windows"

    [[Cares.download]]
    sha256 = "774391885e620847104b9a58a1f22a1f7801a460615c1dd36962c3a7a1ac8b0d"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.i686-w64-mingw32.tar.gz"
[[Cares]]
arch = "powerpc64le"
git-tree-sha1 = "67684679a6fe5a1c8f7af0515823fe0663dae555"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "8ed9a823aec292635d122e7762df5af410dfdf95a50d976467aa7c20351c0d94"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.powerpc64le-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "06fa45cc11803b8212a59cb979044819870f61d5"
os = "macos"

    [[Cares.download]]
    sha256 = "cb3c9e44d0b437af755d03057e62c438dc9d1dfa6a4d304ce6c9d7d98be525e0"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.x86_64-apple-darwin.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "0afa5ca184a33a2e46ec4484b4bd3a7a571d4686"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "d306ae77536fa227446063ff6a20abd7c4b92de5caf7cf9efcc8354249fdff5a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.x86_64-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "a6c148fab5d06e90bf840ea70d95e1ed87823599"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "b9ab605eb7ced22a4b157ae29188cb4434209caec899afadd1936ecf4b90a060"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.x86_64-linux-musl.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "c9ca5b7b3cb1fddf1a8690f249a1c3d2911ea924"
os = "freebsd"

    [[Cares.download]]
    sha256 = "9ded4a80d45ca603b888f099ba744f9602a175ca6d7d6aa2ff672d584a1e6b8b"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.x86_64-unknown-freebsd.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "056dd56601f2240991cbc3054cbf9dd566f25698"
os = "windows"

    [[Cares.download]]
    sha256 = "ad9822b0cbd997aa2d64145de61f6b7f9ace778855c06d0551d1c86dba1db527"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.25.0+0/Cares.v1.25.0.x86_64-w64-mingw32.tar.gz"
