[[Cares]]
arch = "aarch64"
git-tree-sha1 = "c17c65e509e6392860858622bc5962fda672ae1b"
os = "macos"

    [[Cares.download]]
    sha256 = "ab7a6c55c2f229a7129983641f3a04164dd1ac207901355036e03e170d15d581"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.aarch64-apple-darwin.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "9ea16356116e96561d98581eb72d656334e00d95"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "07cd48b5cd20f46bc1392211fe5e9befabc74de62952a7a22735ecd183bf3315"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.aarch64-linux-gnu.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "310707f2de4708ec0ad6e79376cbbb92387ef042"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "adb7d7fa5727115368c27b1b957fbcd550bdb358720ae897e05ca26372bb2875"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.aarch64-linux-musl.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "72763332a028cce5ec45c6e2d1bfd1560c487a1e"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "dbcdadf133d8185d0dc010d1d4d3b26745fda10cdaec1468e52e14999aebbae0"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.armv6l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1040ef493b9e411b0bd0c923590c81defd7dfa5b"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "d38ea8a1bdf14eaf1dac1e586d3404fb7bbd9788ecb4fd9574ff46177924a7c0"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.armv6l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ea3017a30d3a830650043a34f872bd937c1a9c2"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "cd80b007c42069b54a8fe58856553a356031fdf373936210affc26dee4607663"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.armv7l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18ad240766843ddf465b67e5e60a60b0f174062b"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "07d0c1788e57a9b1a4ecba06dbad622c1f73dbe1e1f0c4639be61a7bbc64642e"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.armv7l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "501cb19d37aa138e9a2c09b0e385c53bb8c03807"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "984713b28ab5514e837fb4eb89654c8ec0b2e6987190c1c0ee59a5f82d4a3c67"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.i686-linux-gnu.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "5b252d6e5aff83dac71cfea8e261fdc8f5ae2c8d"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "f522157d473fc12ded124660d094b1f7ea9cee8ffbaa749099a3e5b44ddb16a0"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.i686-linux-musl.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "e368c8f00ddd3b9141c196f2799bca806fb97b75"
os = "windows"

    [[Cares.download]]
    sha256 = "08a6ae1dd1354748e80484441d258e43fafa28579c04266ebf844174e15332c8"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.i686-w64-mingw32.tar.gz"
[[Cares]]
arch = "powerpc64le"
git-tree-sha1 = "1f0f986d5d261450d69df608c8365f589cd5784b"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "2f84e404edb3a7a95991399775c248d86abeaca8bff2feaa0eebc4e2fc337482"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.powerpc64le-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "621540e650e33a2dadd68a953778a6f0994e546b"
os = "macos"

    [[Cares.download]]
    sha256 = "4bde0172556169327dd3f5f72dc9e70a2236b89c6a7105ba1e66378b40175ec3"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.x86_64-apple-darwin.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "00541749774e61801f3ac0a424eb717d51ef28e7"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "6c6dd9b653eaa26f1d00d0e44c97e4e9ceda4f1336bec6437c8d877f508594f8"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.x86_64-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "0d9e0994036e5069ee66d653b01298f400070bee"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "cd718540e6b8a13267cf819e9d6734c4e112570ae439c18e20f4887526d338ce"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.x86_64-linux-musl.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "12f1065b2e3ee0a1eabb92950a92118ccdb9f10e"
os = "freebsd"

    [[Cares.download]]
    sha256 = "741ce8740290f83de0562dc7d8b564af610d983c2fc16befa8f28f48e9c89d1b"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.x86_64-unknown-freebsd.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "700dea259fc8e8fb52a25d2989a701d23e13c70a"
os = "windows"

    [[Cares.download]]
    sha256 = "68b6ea4164d6a6fbd6272b70023e9fa0c1dd0d3548147c55b4a44089e437824d"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.19.0+0/Cares.v1.19.0.x86_64-w64-mingw32.tar.gz"
