[[Cares]]
arch = "aarch64"
git-tree-sha1 = "b152436f2a262e8188e656b6c0790ae9ed5ce327"
os = "macos"

    [[Cares.download]]
    sha256 = "a14945cba1aab8d6a0598a6d2ed93da086522e96099b305e1704899cecfcb6c2"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.aarch64-apple-darwin.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "149f89e2cc1da9dd0175d73034bf561fd083e37e"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "3c34c58afb47b32ae60fd6692436ab982045158fb58b31c5c6b84004a3a65afd"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.aarch64-linux-gnu.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "a05d39f47d2e6f8020646fd76fda99c22196e1a0"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "7941f5c46fee1bf52947a8efee2875ba8731fad4ddd59eeae0ca139fecb9c222"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.aarch64-linux-musl.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02f6312e19c9e62288be447d80f7607e8056cc4b"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "89b0a27f6f94d9a602dd7dbb72efcaab2629ad7ffc68b25488178ad53969ed55"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.armv6l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6b9171438c834b991a496190a69daea2db2068b8"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "6fcb9d988708fc3ca7c8ae8848cb78d26c8e58b7c90138501fa9bf8e66031ee4"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.armv6l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8b679b8ef9a030c1787aee2e62b4815e8b83eae4"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "8be8fe83b4b27a8b46f517171e3fc71739c8b7f831b584b7ac97f0c3a194ed61"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.armv7l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc3e7c38e3b43b89b74ebe447b885b4567da6a8c"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "b967f9b6af26dd8df7cb8fe11d276882f05da6a88061b0267cd2fa924775058a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.armv7l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "58790cf134df57f4403ec210d94f73aeff6d76a4"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "bba358205bc1dabb8923d42e3d5117e98161fa15d0b4242a10be66376f032717"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.i686-linux-gnu.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "1a8e6f9e9e1b070153b116fa56fcf2ed6de8aa3f"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "503642d84341128926876ed46454e4ce23b12417331aa363b572d8b4c871df08"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.i686-linux-musl.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "a832708d47bc6b2e29aa44235c524f7de2cf26c6"
os = "windows"

    [[Cares.download]]
    sha256 = "5c436ea86fc6100ca7eab1222a2d076af6f1cc3ca706a34bbcbde47063c17556"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.i686-w64-mingw32.tar.gz"
[[Cares]]
arch = "powerpc64le"
git-tree-sha1 = "198f70577a0602ed60569d4e885e824ea86dbe54"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "9931b2df7c8b1ccf66ab78617cc1e173bcec11b7b966a70d130bf75019c8bae4"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.powerpc64le-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "c74fcf6a8a2015d498c4be58975c7dc2ed0fc0f1"
os = "macos"

    [[Cares.download]]
    sha256 = "982b8cfcf9caaa2363711bd360087beb5cd5919e1a4ed9d48e5c01c2ed5709c9"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.x86_64-apple-darwin.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "292d7b8b6a2abc110f75020fa01d59f76710b8f9"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "7aa16f458bcbdc6f8137f1f9483c1692b4174125691f1b449edd471b6ef340d0"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.x86_64-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "b5b49067ccfd24ea448c2be3119f1bf7c27fab65"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "0355568a9714d36acefd5c72d6607de1a08eb3d4135931fa201fc72571b79ad6"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.x86_64-linux-musl.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "ea70d6af3e116f48f247f5aa6647c93169704003"
os = "freebsd"

    [[Cares.download]]
    sha256 = "f820a6516fe8aff0f01c2076b95abfa70d00ba56d1b4bd1dc2986e31f46b40e3"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.x86_64-unknown-freebsd.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "6bf171827a5a8089338b24db530f8a58c823e9ec"
os = "windows"

    [[Cares.download]]
    sha256 = "14738b138dd6815de2c0b8fa236a88fe8c64df26fcf130260416359cbec2f8c7"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.24.0+0/Cares.v1.24.0.x86_64-w64-mingw32.tar.gz"
