[[Cares]]
arch = "aarch64"
git-tree-sha1 = "28fa5425812f87ac24f4fb5d69f885b5831b49c2"
os = "macos"

    [[Cares.download]]
    sha256 = "df8a8f43c5c9f7f7d3d29d58770f0b5e4f7cadef2d1ff647f8af50277a74efca"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.aarch64-apple-darwin.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "8bf4213e4c9ede1eee0ec4ef65f5692a0745d465"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "2799c1664e63ad9e155730c25ef2bc94a3d086bc2d0be435b62077605619d9d2"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.aarch64-linux-gnu.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "92149549fa4f6fed174f82ea847243ba1ae77a3e"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "ad007e60f25a18113215d2f847578b7db791881b61608b588b95970b5805f12d"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.aarch64-linux-musl.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd40630fffa058deb23c3eeeac21accf80f7d14d"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "108673e87c7ab82f8dae276a456346f1790f4bda5e3e0f61bb29f2d47cce5d22"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.armv6l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7a889f54019554437b15b08ed7d134cbff84c475"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "f1d11586b1875067c6f93187798fc441a87375306a7bc604b041ca989585d550"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.armv6l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40cc2f346f6e8e4386fae891b63ee4748b48fdb1"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "a94cb74146af949754fbcf1a89b3ea8a723de289d8a7944f0c4bfcbf7376223a"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.armv7l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7bc405402d4e7b18317178b65fe9b0b65d12bd98"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "9919415372a206bdd174ddad1d9d1658658ff1f5be3f77939edbe734c1e58ed4"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.armv7l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "e35774358f7f8ab6ddfbf68a82450c6e326cc031"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "67db022dee3862295e6488a8bac853306a2db260269f4b9f9d143912e7b04647"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.i686-linux-gnu.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "8e9a09e686b57f1afbd37b2bc20b1505ddf16fed"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "bd2d967586394cdc56213c84de02deda8be569781540c2d862a17421c0e836c8"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.i686-linux-musl.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "735141ff4e3b32c1a79ec428082ef49ff52a9b6a"
os = "windows"

    [[Cares.download]]
    sha256 = "de28dca8b8844b0c591fbccaac774df2c4568f3be84389900c8f4f14d49d1c44"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.i686-w64-mingw32.tar.gz"
[[Cares]]
arch = "powerpc64le"
git-tree-sha1 = "d4ebbb5ada15ba4dd8ff0b655462ecffc8344865"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "7432fd9d79ec91da8e15194c8405c3705e641f86bccf7d2d808b63325068d7d5"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.powerpc64le-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "51cd014bac23794404d0405e2ceacb9b71f0f492"
os = "macos"

    [[Cares.download]]
    sha256 = "78895a506679b98b04790812808e8196af2d3de1c58870b045c0fecd80a6ce72"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.x86_64-apple-darwin.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "cc3fd0fe18c741d7a16d5a693a3b1a5131f4592e"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "ee9bdf446e5867e4a5d956080177f48b2b64484893c09b0aff81ddd3145db040"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.x86_64-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "26a785eda7f366871fdfd65ff21101741fa842a1"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "efba4022de2d31c821d6012389a908c6ba9f8481abc1fb978b64f2f0169108e4"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.x86_64-linux-musl.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "13ccfc6c082741e39e15d28d1c082e4cdd1c2354"
os = "freebsd"

    [[Cares.download]]
    sha256 = "2e1072095a03a3b7f1f4aadf7db126f3dde196e67bc1d2998dfb130f034125b4"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.x86_64-unknown-freebsd.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "d9c63ad3879d212e3d89347ef954ad3b5c11744e"
os = "windows"

    [[Cares.download]]
    sha256 = "b9647d9314ae91fee829b51ceec8a7cba9e32b5feba7906f2261696ad8bfe35e"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.27.0+0/Cares.v1.27.0.x86_64-w64-mingw32.tar.gz"
