[[Cares]]
arch = "aarch64"
git-tree-sha1 = "ff168d2134c29a1fc0acf09a16bd5f47985709d1"
os = "macos"

    [[Cares.download]]
    sha256 = "707f72e43c9c47bbe2d2c5ec6b6a6999fb3f1ace9100d23a0dfa40147444418e"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.aarch64-apple-darwin.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "3ed1a892016feed5c71c89238a7526da64564b30"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "c08ca4b8efca27e3361491b84ba3eb6f7c18377f7ed0d3260dd8014b01a44c29"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.aarch64-linux-gnu.tar.gz"
[[Cares]]
arch = "aarch64"
git-tree-sha1 = "bfc6333681397a56b5d33416e9ff31373941dcbe"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "1ca005f2ffcf96d1ef0f9295b303b786c2316d997ee4995fffcefabd3215edc7"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.aarch64-linux-musl.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60adb35c26560986ccf969a5bc3853aa7e211c68"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "ab956eb5ca8c1521fc07465e25c9d6401368e0513f5e972b2c11078fad85f7f5"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.armv6l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6414fdae60023b14961c8b35b4320e2b054f272"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "b62656ec5cb333dfe040964dc6b79a071f5a739a49369638d0788a4dc7f09f96"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.armv6l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81da977afa5dc32bcebd07a0cc67aa10e8fe0fb8"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "c2c22e7152cabdbb6d247ce9efc54c49acf34794f27ce519c9c81d15d24964b8"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.armv7l-linux-gnueabihf.tar.gz"
[[Cares]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b5d6c31d7beabd5c4f80166e8e5ec58e95a51f04"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "5c49b0d78836e6e9a0e79f2ad43ffae667a44f9ad9692992cbfc1df692db6b4f"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.armv7l-linux-musleabihf.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "bc071c00ef4d758d687a3337fe37d6d84b5cb947"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "7450f830ffa158ec2a45cd7b76445fd1b1aaf49c7d45ce1be9c652217d21fbf4"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.i686-linux-gnu.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "966ec225a65fdb54c8d81723a42460d37b647862"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "63e603911e63522fbf8bc7f3a6542ce119036bff17fd3028101a9a252edb4ea1"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.i686-linux-musl.tar.gz"
[[Cares]]
arch = "i686"
git-tree-sha1 = "5453ad6e48d014ba8615870fc55e0e372091f4b9"
os = "windows"

    [[Cares.download]]
    sha256 = "5ad0ad2d195c4e5d9ecc5a06dd6ff44eb2f815f0db2fc65a9229d2fd71d6a207"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.i686-w64-mingw32.tar.gz"
[[Cares]]
arch = "powerpc64le"
git-tree-sha1 = "5efd4793d15bd30e0b6486a457fd6f61afa96383"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "8ea49532c6cb3588ae6f471302a17660400c0be97eb4a4584f362a18c143a538"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.powerpc64le-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "8fc7d9ccc9fc30d9b41d1e6e08339a5728efad5f"
os = "macos"

    [[Cares.download]]
    sha256 = "15a2377104d32f128b49410689bcfde071e5e2af2a62839cacc8155e8913c142"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.x86_64-apple-darwin.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "562a896ac9d51aba21f70540ee5e1c54d37734d2"
libc = "glibc"
os = "linux"

    [[Cares.download]]
    sha256 = "5008a461838be103e51e8045e8d24670ee37d53a53ff8c7ccac20e2804c40f95"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.x86_64-linux-gnu.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "04b59b18abf3f1aa7011e23780d5c3e1926d41f2"
libc = "musl"
os = "linux"

    [[Cares.download]]
    sha256 = "e496255a80fe23f4885704374d6085e475c827070145ed65f360002a4eb9f245"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.x86_64-linux-musl.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "3acde03289e5fd4ddfb1dc2171b575ded216ca9e"
os = "freebsd"

    [[Cares.download]]
    sha256 = "2ce29c105bab6fd7def86bb5032fb6b35a3f1bca2c00088700a74cb33e6aefb5"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.x86_64-unknown-freebsd.tar.gz"
[[Cares]]
arch = "x86_64"
git-tree-sha1 = "8c2357e61f90451111a43c2593ed04462db89fea"
os = "windows"

    [[Cares.download]]
    sha256 = "5c97dfbba123a093d236c2c97ecd923944a3e86e37baa24831d47674790f19b0"
    url = "https://github.com/JuliaBinaryWrappers/Cares_jll.jl/releases/download/Cares-v1.32.3+0/Cares.v1.32.3.x86_64-w64-mingw32.tar.gz"
